-- Clear existing sample data first
DELETE FROM public.availability_rules WHERE spot_id IN (SELECT id FROM public.spots);
DELETE FROM public.spot_photos WHERE spot_id IN (SELECT id FROM public.spots);
DELETE FROM public.spots;

-- Insert diverse parking spots across LA neighborhoods with real addresses
INSERT INTO public.spots (
  host_id, title, description, address, latitude, longitude, location,
  hourly_rate, daily_rate, has_ev_charging, is_covered, is_secure,
  access_notes, host_rules, status, size_constraints
) VALUES 
-- University Park (USC area) - 4 spots
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'USC Campus Adjacent Garage',
  'Covered parking just steps from USC campus. Perfect for students, faculty, and visitors.',
  '1234 S Figueroa Street, Los Angeles, CA 90007',
  34.0224,
  -118.2851,
  ST_GeogFromText('POINT(-118.2851 34.0224)'),
  8.00,
  55.00,
  false,
  true,
  true,
  'Enter through main gate, spot B-12. Show parking pass to security.',
  'USC visitors welcome. No overnight parking during finals week.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Exposition Park Driveway',
  'Safe residential parking near museums and USC. Easy metro access.',  
  '789 W 37th Place, Los Angeles, CA 90007',
  34.0195,
  -118.2845,
  ST_GeogFromText('POINT(-118.2845 34.0195)'),
  6.00,
  40.00,
  true,
  false,
  true,
  'Park behind the white Tesla. Ring doorbell #2 if needed.',
  'Respectful visitors only. No parties or loud music.',
  'active',
  '{compact,midsize,suv}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Vermont/Exposition Lot',
  'Open lot with security cameras. Walk to USC, museums, and Metro.',
  '456 S Vermont Avenue, Los Angeles, CA 90007', 
  34.0189,
  -118.2920,
  ST_GeogFromText('POINT(-118.2920 34.0189)'),
  5.00,
  35.00,
  false,
  false,
  true,
  'Spot #47 near the fence. Pay attendant or use app.',
  'Daytime parking only. Lot closes at 10 PM.',
  'active',
  '{compact,midsize,suv,truck}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Historic West Adams Mansion',
  'Victorian era mansion with private gated parking. Unique experience!',
  '2123 S Harvard Boulevard, Los Angeles, CA 90007',
  34.0156,
  -118.2895,
  ST_GeogFromText('POINT(-118.2895 34.0156)'),
  12.00,
  80.00,
  false,
  false,
  true,
  'Use gate code 1908. Park in designated visitor area.',
  'Historical property - please be respectful. No smoking.',
  'active',
  '{compact,midsize}'
),

-- Santa Monica - 6 spots  
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Santa Monica Pier Parking',
  'Premium spot just 2 blocks from the iconic pier and beach!',
  '123 Ocean Avenue, Santa Monica, CA 90401',
  34.0195,
  -118.4912,
  ST_GeogFromText('POINT(-118.4912 34.0195)'),
  15.00,
  95.00,
  false,
  false,
  true,
  'Spot is on Ocean Ave side. Beach gear storage available.',
  'Beach visitors welcome! No sand in cars please.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Third Street Promenade Garage',
  'Covered downtown Santa Monica parking. Shopping and dining steps away.',
  '456 3rd Street, Santa Monica, CA 90401',
  34.0141,
  -118.4958,
  ST_GeogFromText('POINT(-118.4958 34.0141)'),
  12.00,
  75.00,
  true,
  true,
  true,
  'Level 2, Section C. Elevator to promenade level.',
  'Shopper friendly. Validate for discounts at participating stores.',
  'active',
  '{compact,midsize,suv}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Main Street Venice Border',
  'Artistic neighborhood parking near galleries and cafes.',
  '789 Main Street, Santa Monica, CA 90405',
  34.0045,
  -118.4789,
  ST_GeogFromText('POINT(-118.4789 34.0045)'),
  9.00,
  60.00,
  false,
  false,
  false,
  'Street parking in front of blue building. Meter not required weekends.',
  'Artists and creatives welcome! Support local businesses.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Pico Boulevard Business Hub',
  'Central Santa Monica location perfect for business meetings.',
  '1011 Pico Boulevard, Santa Monica, CA 90405',
  34.0084, 
  -118.4856,
  ST_GeogFromText('POINT(-118.4856 34.0084)'),
  10.00,
  65.00,
  true,
  true,
  true,
  'Business center parking. Reception can validate.',
  'Business attire recommended. Quiet zone - no loud calls.',
  'active',
  '{compact,midsize,suv}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Santa Monica College Area',
  'Student-friendly parking near SMC campus and bus lines.',
  '1212 Pico Boulevard, Santa Monica, CA 90405',
  34.0092,
  -118.4823,
  ST_GeogFromText('POINT(-118.4823 34.0092)'),
  7.00,
  45.00,
  false,
  false,
  true,
  'Student discounts available. Show student ID.',
  'Students welcome! Study groups OK in common area.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Wilshire Boulevard Office Complex',
  'Professional building with premium amenities and valet.',
  '1515 Wilshire Boulevard, Santa Monica, CA 90403',
  34.0259,
  -118.4695,
  ST_GeogFromText('POINT(-118.4695 34.0259)'),
  18.00,
  120.00,
  true,
  true,
  true,
  'Valet service available. Business center access included.',
  'Professional environment. Business casual required.',
  'active',
  '{midsize,suv}'
),

-- West Hollywood - 3 spots
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Sunset Strip Premium',
  'Heart of the action! Walk to legendary clubs and restaurants.',
  '8901 Sunset Boulevard, West Hollywood, CA 90069',
  34.0900,
  -118.3617,
  ST_GeogFromText('POINT(-118.3617 34.0900)'),
  20.00,
  140.00,
  false,
  true,
  true,
  'VIP entrance through lobby. Concierge available 24/7.',
  'Nightlife enthusiasts welcome! No noise after midnight.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Melrose Design District',
  'Trendy area perfect for shopping vintage and designer stores.',
  '567 N Melrose Avenue, West Hollywood, CA 90038', 
  34.0836,
  -118.3734,
  ST_GeogFromText('POINT(-118.3734 34.0836)'),
  14.00,
  85.00,
  false,
  false,
  true,
  'Street parking with 2-hour validation at participating shops.',
  'Fashion lovers paradise! Tag us in your shopping photos.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Santa Monica Blvd Hub',
  'Central WeHo location with easy access to everything.',
  '234 Santa Monica Boulevard, West Hollywood, CA 90069',
  34.0901,
  -118.3712,
  ST_GeogFromText('POINT(-118.3712 34.0901)'),
  16.00,
  95.00,
  true,
  false,
  true,
  'Metered street parking. Mobile payment accepted.',
  'LGBTQ+ friendly zone. Respect and love for all!',
  'active',
  '{compact,midsize,suv}'
),

-- Beverly Hills - 2 spots
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Rodeo Drive Luxury',
  'Exclusive parking steps from world-famous luxury shopping.',
  '345 N Rodeo Drive, Beverly Hills, CA 90210',
  34.0736,
  -118.4004,
  ST_GeogFromText('POINT(-118.4004 34.0736)'),
  25.00,
  180.00,
  false,
  true,
  true,
  'Valet parking available. Concierge shopping assistance.',
  'Luxury experience only. Dress code enforced.',
  'active',
  '{midsize,suv}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Beverly Hills City Hall',
  'Convenient parking for city business and nearby attractions.',
  '455 N Rexford Drive, Beverly Hills, CA 90210',
  34.0721,
  -118.4034,
  ST_GeogFromText('POINT(-118.4034 34.0721)'),
  15.00,
  90.00,
  true,
  false,
  true,
  'Public parking structure. Take ticket at entrance.',
  'Civic center parking. Business hours preferred.',
  'active',
  '{compact,midsize,suv}'
),

-- Venice - 3 spots
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Venice Beach Boardwalk',
  'Iconic beachfront parking! Watch street performers and surfers.',
  '678 Ocean Front Walk, Venice, CA 90291',
  34.0052,
  -118.4810,
  ST_GeogFromText('POINT(-118.4810 34.0052)'),
  12.00,
  70.00,
  false,
  false,
  false,
  'Beach parking - bring quarters for meters. Sand cleanup fee may apply.',
  'Beach vibes only! Swimwear welcome. No glass containers.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Abbot Kinney Creative District',
  'Hip area with boutiques, galleries, and artisanal coffee shops.',
  '1234 Abbot Kinney Boulevard, Venice, CA 90291',
  34.0043,
  -118.4756,
  ST_GeogFromText('POINT(-118.4756 34.0043)'),
  11.00,
  65.00,
  true,
  false,
  true,
  'Creative district parking. Support local artists and businesses!',
  'Artists and free spirits welcome. Good vibes only.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Venice Canals Historic',
  'Peaceful residential area near the historic Venice canal system.',
  '567 Dell Avenue, Venice, CA 90291',
  34.0018,
  -118.4721,
  ST_GeogFromText('POINT(-118.4721 34.0018)'),
  8.00,
  50.00,
  false,
  false,
  true,
  'Quiet residential street. Perfect for canal walks.',
  'Respect the neighborhood. Quiet hours after 9 PM.',
  'active',
  '{compact,midsize}'
),

-- Downtown LA - 5 spots
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Staples Center Event Parking',
  'Prime location for Lakers, Clippers, and concert events!',
  '1111 S Figueroa Street, Los Angeles, CA 90015',
  34.0430,
  -118.2673,
  ST_GeogFromText('POINT(-118.2673 34.0430)'),
  30.00,
  200.00,
  false,
  true,
  true,
  'Event parking premium rates. Book early for big games!',
  'Sports fans welcome! Team jerseys encouraged.',
  'active',
  '{compact,midsize,suv,truck}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Arts District Loft',
  'Trendy arts district with galleries, breweries, and lofts.',
  '789 E 3rd Street, Los Angeles, CA 90013',
  34.0378,
  -118.2345,
  ST_GeogFromText('POINT(-118.2345 34.0378)'),
  9.00,
  55.00,
  true,
  false,
  true,
  'Industrial chic area. Brewery hopping encouraged!',
  'Art lovers and creatives welcome. Instagram worthy spots nearby.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Grand Central Market',
  'Historic food hall parking. Experience LAs culinary diversity.',
  '317 S Broadway, Los Angeles, CA 90013',
  34.0506,
  -118.2508,
  ST_GeogFromText('POINT(-118.2508 34.0506)'),
  13.00,
  75.00,
  false,
  true,
  true,
  'Historic building parking. Food hall validation available.',
  'Foodies paradise! Try the famous egg sandwiches.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Little Tokyo Cultural Hub',
  'Experience authentic Japanese culture and cuisine.',
  '456 E 1st Street, Los Angeles, CA 90012',
  34.0506,
  -118.2389,
  ST_GeogFromText('POINT(-118.2389 34.0506)'),
  10.00,
  60.00,
  false,
  false,
  true,
  'Cultural district parking. Visit the Japanese American Museum!',
  'Cultural enthusiasts welcome. Remove shoes at some venues.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Financial District High-Rise',
  'Corporate parking in the heart of LAs business district.',
  '123 S Hope Street, Los Angeles, CA 90071',
  34.0522,
  -118.2512,
  ST_GeogFromText('POINT(-118.2512 34.0522)'),
  22.00,
  150.00,
  true,
  true,
  true,
  'Corporate rates available. Business center access included.',
  'Professional environment. Business attire required.',
  'active',
  '{midsize,suv}'
),

-- Hollywood - 2 spots
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Hollywood Walk of Fame',
  'See your favorite stars on the famous sidewalk!',
  '6801 Hollywood Boulevard, Los Angeles, CA 90028',
  34.1022,
  -118.3406,
  ST_GeogFromText('POINT(-118.3406 34.1022)'),
  18.00,
  110.00,
  false,
  false,
  true,
  'Tourist central! Bring your camera for star photos.',
  'Tourist friendly. Street performers and characters nearby.',
  'active',
  '{compact,midsize}'
),
(
  (SELECT user_id FROM public.profiles LIMIT 1),
  'Griffith Observatory Area',
  'Scenic parking near the iconic observatory and hiking trails.',
  '2800 E Observatory Road, Los Angeles, CA 90027',
  34.1184,
  -118.3004,
  ST_GeogFromText('POINT(-118.3004 34.1184)'),
  8.00,
  45.00,
  false,
  false,
  false,
  'Scenic mountain parking. Great for hikers and stargazers.',
  'Nature lovers welcome! Bring hiking boots and water.',
  'active',
  '{compact,midsize,suv}'
);

-- Add availability rules (24/7 for all spots)
INSERT INTO public.availability_rules (spot_id, day_of_week, start_time, end_time, is_available)
SELECT 
  s.id,
  generate_series(0, 6) as day_of_week,
  '00:00:00'::time,
  '23:59:59'::time,
  true
FROM public.spots s;